### ISSUE TITLE
duplicate `react-scripts` dependencies

### ISSUE THREAD

**Issue by wholegroup** [Maintstar/ms-mui#10]
package.json contains 2 dependencies of `react-script`
in `dependencies` section and `devDependencies` section

right way to leave this package only on `devDependencies`

**Comment by wholegroup** [comment]
we need to fix this issue because it breaks our jest tests since `react-scripts` contains old jest dependency.

**Comment by vladimirbuskin** [comment]
ok, thank you, did with https://github.com/Maintstar/ms-mui/commit/e4fc3a6c7e251db84225950d6c7dba414918cc5e
